# Generated by Django 4.0.10 on 2024-05-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_totalwinnings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalwinnings',
            options={'verbose_name_plural': 'Total Winnings'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_winnings',
        ),
    ]
