# Generated by Django 4.0.10 on 2024-05-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_totalwinnings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalwinnings',
            name='source',
            field=models.CharField(choices=[('PAID_GAME', 'Paid Game'), ('FREE_GAME', 'Free Game'), ('PROMO', 'Promo')], default=('FREE_GAME', 'FREE GAME'), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalwinnings',
            name='wallet_credited',
            field=models.CharField(choices=[('main_account_balance', 'Main Account'), ('bonus_account_balance', 'Bonus Account')], default=('MAIN_ACCOUNT', 'Main Account'), max_length=254),
            preserve_default=False,
        ),
    ]
